### PR TITLE
Ensure compatibility with mocap_interfaces and mocap REP Standards

### PR DESCRIPTION
**Pull request by aaggj**
# Ensure compatibility with `mocap_interfaces` and `mocap REP` Standards

## PR Description

This PR introduces the following changes to ensure full compliance with the `mocap_interfaces` package and the `mocap REP` specifications:

- **Server address update**: The server address has been updated to ensure proper connectivity.
- **Compliance with `mocap_interfaces` and `mocap REP`**: All files have been modified to align with the requirements outlined in the `mocap REP`. This includes updates to the OptiTrack driver for compatibility.
- **Modification of `package.xml`**: The `package.xml` file has been updated to reflect the necessary changes in dependencies and configuration.

These changes enhance the package’s compatibility and adherence to the latest standards in motion capture systems within ROS 2.

### CODE REVIEW

**Comment by fmrico** [comment]
Hi @aaggj 

Why is this failing?

**Comment by aaggj** [comment]
Hi @fmrico, it is failing because it does not find the mocap interfaces package, I am trying to fix it

**Comment by aaggj** [comment]
It worked in my fork, so it should work

**Comment by fmrico** [comment]
Use the  `vcs-repo-file-url: ${GITHUB_WORKSPACE}/dependency_repos.repos` approach

**Comment by aaggj** [comment]
Done

**Comment by Juancams** [comment]
You are in rolling, and rolling is 24. The CI is running in 22

**Pull request merged**
